In [ ]:
#PCA = #Dimensionality reduction 

In [72]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import os

In [73]:
pwd

'C:\\Users\\ABC\\6. Datasets'

In [74]:
os.chdir('C:\\Users\\ABC\\6. Datasets')

In [75]:
dataset = pd.read_csv('wine.csv')

In [76]:
dataset.head()

Alcohol  Malic.acid   Ash   Acl   Mg  Phenols  Flavanoids  \
0    14.23        1.71  2.43  15.6  127     2.80        3.06   
1    13.20        1.78  2.14  11.2  100     2.65        2.76   
2    13.16        2.36  2.67  18.6  101     2.80        3.24   
3    14.37        1.95  2.50  16.8  113     3.85        3.49   
4    13.24        2.59  2.87  21.0  118     2.80        2.69   

   Nonflavanoid.phenols  Proanth  Color.int   Hue    OD  Proline  Wine  
0                  0.28     2.29       5.64  1.04  3.92     1065     1  
1                  0.26     1.28       4.38  1.05  3.40     1050     1  
2                  0.30     2.81       5.68  1.03  3.17     1185     1  
3                  0.24     2.18       7.80  0.86  3.45     1480     1  
4                  0.39     1.82       4.32  1.04  2.93      735     1

In [97]:
dataset.shape

(178, 14)

In [77]:
#Splitting the dataset into features and targets

x = dataset.iloc[:,:-1]
y = dataset.iloc[:,-1]

In [78]:
x.head()

Alcohol  Malic.acid   Ash   Acl   Mg  Phenols  Flavanoids  \
0    14.23        1.71  2.43  15.6  127     2.80        3.06   
1    13.20        1.78  2.14  11.2  100     2.65        2.76   
2    13.16        2.36  2.67  18.6  101     2.80        3.24   
3    14.37        1.95  2.50  16.8  113     3.85        3.49   
4    13.24        2.59  2.87  21.0  118     2.80        2.69   

   Nonflavanoid.phenols  Proanth  Color.int   Hue    OD  Proline  
0                  0.28     2.29       5.64  1.04  3.92     1065  
1                  0.26     1.28       4.38  1.05  3.40     1050  
2                  0.30     2.81       5.68  1.03  3.17     1185  
3                  0.24     2.18       7.80  0.86  3.45     1480  
4                  0.39     1.82       4.32  1.04  2.93      735

In [79]:
from sklearn.model_selection import train_test_split

In [117]:
#Splittng data into training and testing 
x_train, x_test, y_train,y_test = train_test_split(x,y, test_size = 0.2, random_state = 0)

In [124]:
dataset['test/train'] = 'train'
dataset.loc[dataset.index.isin(x_test.index), 'test/train'] = 'test'
dataset.loc[dataset['test/train']== 'test']

Alcohol  Malic.acid   Ash   Acl   Mg  Phenols  Flavanoids  \
4      13.24        2.59  2.87  21.0  118     2.80        2.69   
5      14.20        1.76  2.45  15.2  112     3.27        3.39   
7      14.06        2.15  2.61  17.6  121     2.60        2.51   
8      14.83        1.64  2.17  14.0   97     2.80        2.98   
18     14.19        1.59  2.48  16.5  108     3.30        3.93   
26     13.39        1.77  2.62  16.1   93     2.85        2.94   
33     13.76        1.53  2.70  19.5  132     2.95        2.74   
37     13.05        1.65  2.55  18.0   98     2.45        2.43   
44     13.05        1.77  2.10  17.0  107     3.00        3.00   
45     14.21        4.04  2.44  18.9  111     2.85        2.65   
51     13.83        1.65  2.60  17.2   94     2.45        2.99   
54     13.74        1.67  2.25  16.4  118     2.60        2.90   
55     13.56        1.73  2.46  20.5  116     2.96        2.78   
56     14.22        1.70  2.30  16.3  118     3.20        3.00   
60     12.33        1.10  2.28  16.0  101     2.05        1.09   
61     12.64        1.36  2.02  16.8  100     2.02        1.41   
63     12.37        1.13  2.16  19.0   87     3.50        3.10   
66     13.11        1.01  1.70  15.0   78     2.98        3.18   
80     12.00        0.92  2.00  19.0   86     2.42        2.26   
86     12.16        1.61  2.31  22.8   90     1.78        1.69   
90     12.08        1.83  2.32  18.5   81     1.60        1.50   
98     12.37        1.07  2.10  18.5   88     3.52        3.75   
104    12.51        1.73  1.98  20.5   85     2.20        1.92   
106    12.25        1.73  2.12  19.0   80     1.65        2.03   
111    12.52        2.43  2.17  21.0   88     2.55        2.27   
112    11.76        2.68  2.92  20.0  103     1.75        2.03   
121    11.56        2.05  3.23  28.5  119     3.18        5.08   
123    13.05        5.80  2.13  21.5   86     2.62        2.65   
126    12.43        1.53  2.29  21.5   86     2.74        3.15   
129    12.04        4.30  2.38  22.0   80     2.10        1.75   
141    13.36        2.56  2.35  20.0   89     1.40        0.50   
146    13.88        5.04  2.23  20.0   80     0.98        0.34   
151    12.79        2.67  2.48  22.0  112     1.48        1.36   
160    12.36        3.83  2.38  21.0   88     2.30        0.92   
164    13.78        2.76  2.30  22.0   90     1.35        0.68   
168    13.58        2.58  2.69  24.5  105     1.55        0.84   

     Nonflavanoid.phenols  Proanth  Color.int   Hue    OD  Proline  Wine  \
4                    0.39     1.82       4.32  1.04  2.93      735     1   
5                    0.34     1.97       6.75  1.05  2.85     1450     1   
7                    0.31     1.25       5.05  1.06  3.58     1295     1   
8                    0.29     1.98       5.20  1.08  2.85     1045     1   
18                   0.32     1.86       8.70  1.23  2.82     1680     1   
26                   0.34     1.45       4.80  0.92  3.22     1195     1   
33                   0.50     1.35       5.40  1.25  3.00     1235     1   
37                   0.29     1.44       4.25  1.12  2.51     1105     1   
44                   0.28     2.03       5.04  0.88  3.35      885     1   
45                   0.30     1.25       5.24  0.87  3.33     1080     1   
51                   0.22     2.29       5.60  1.24  3.37     1265     1   
54                   0.21     1.62       5.85  0.92  3.20     1060     1   
55                   0.20     2.45       6.25  0.98  3.03     1120     1   
56                   0.26     2.03       6.38  0.94  3.31      970     1   
60                   0.63     0.41       3.27  1.25  1.67      680     2   
61                   0.53     0.62       5.75  0.98  1.59      450     2   
63                   0.19     1.87       4.45  1.22  2.87      420     2   
66                   0.26     2.28       5.30  1.12  3.18      502     2   
80                   0.30     1.43       2.50  1.38  3.12      278     2   
86                   0.43     1.56       2

In [81]:
#Feature scaling
from sklearn.preprocessing import StandardScaler
stndS = StandardScaler()
x_train = stndS.fit_transform(x_train)
x_test = stndS.transform(x_test)

In [86]:
from sklearn.decomposition import PCA
pca = PCA(n_components=2)
x_train = pca.fit_transform(x_train) #This wil reduce n. f fetures from 13 to 2. RUn it and see
x_test = pca.transform(x_test)

In [87]:
from sklearn.linear_model import LogisticRegression
classifier = LogisticRegression()
classifier.fit(x_train, y_train)

LogisticRegression()

In [90]:
from sklearn.metrics import confusion_matrix, accuracy_score
y_pred = classifier.predict(x_test)
cm = confusion_matrix(y_test,y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[14  0  0]
 [ 1 15  0]
 [ 0  0  6]]


0.9722222222222222

In [98]:
results = pd.DataFrame({'y_test' : y_test, 'y_pred': y_pred})
y_test.shape

(36,)

In [101]:
df = pd.merge(dataset, results, left_index = True,  right_index = True)
df

Alcohol  Malic.acid   Ash   Acl   Mg  Phenols  Flavanoids  \
4      13.24        2.59  2.87  21.0  118     2.80        2.69   
5      14.20        1.76  2.45  15.2  112     3.27        3.39   
7      14.06        2.15  2.61  17.6  121     2.60        2.51   
8      14.83        1.64  2.17  14.0   97     2.80        2.98   
18     14.19        1.59  2.48  16.5  108     3.30        3.93   
26     13.39        1.77  2.62  16.1   93     2.85        2.94   
33     13.76        1.53  2.70  19.5  132     2.95        2.74   
37     13.05        1.65  2.55  18.0   98     2.45        2.43   
44     13.05        1.77  2.10  17.0  107     3.00        3.00   
45     14.21        4.04  2.44  18.9  111     2.85        2.65   
51     13.83        1.65  2.60  17.2   94     2.45        2.99   
54     13.74        1.67  2.25  16.4  118     2.60        2.90   
55     13.56        1.73  2.46  20.5  116     2.96        2.78   
56     14.22        1.70  2.30  16.3  118     3.20        3.00   
60     12.33        1.10  2.28  16.0  101     2.05        1.09   
61     12.64        1.36  2.02  16.8  100     2.02        1.41   
63     12.37        1.13  2.16  19.0   87     3.50        3.10   
66     13.11        1.01  1.70  15.0   78     2.98        3.18   
80     12.00        0.92  2.00  19.0   86     2.42        2.26   
86     12.16        1.61  2.31  22.8   90     1.78        1.69   
90     12.08        1.83  2.32  18.5   81     1.60        1.50   
98     12.37        1.07  2.10  18.5   88     3.52        3.75   
104    12.51        1.73  1.98  20.5   85     2.20        1.92   
106    12.25        1.73  2.12  19.0   80     1.65        2.03   
111    12.52        2.43  2.17  21.0   88     2.55        2.27   
112    11.76        2.68  2.92  20.0  103     1.75        2.03   
121    11.56        2.05  3.23  28.5  119     3.18        5.08   
123    13.05        5.80  2.13  21.5   86     2.62        2.65   
126    12.43        1.53  2.29  21.5   86     2.74        3.15   
129    12.04        4.30  2.38  22.0   80     2.10        1.75   
141    13.36        2.56  2.35  20.0   89     1.40        0.50   
146    13.88        5.04  2.23  20.0   80     0.98        0.34   
151    12.79        2.67  2.48  22.0  112     1.48        1.36   
160    12.36        3.83  2.38  21.0   88     2.30        0.92   
164    13.78        2.76  2.30  22.0   90     1.35        0.68   
168    13.58        2.58  2.69  24.5  105     1.55        0.84   

     Nonflavanoid.phenols  Proanth  Color.int   Hue    OD  Proline  Wine  \
4                    0.39     1.82       4.32  1.04  2.93      735     1   
5                    0.34     1.97       6.75  1.05  2.85     1450     1   
7                    0.31     1.25       5.05  1.06  3.58     1295     1   
8                    0.29     1.98       5.20  1.08  2.85     1045     1   
18                   0.32     1.86       8.70  1.23  2.82     1680     1   
26                   0.34     1.45       4.80  0.92  3.22     1195     1   
33                   0.50     1.35       5.40  1.25  3.00     1235     1   
37                   0.29     1.44       4.25  1.12  2.51     1105     1   
44                   0.28     2.03       5.04  0.88  3.35      885     1   
45                   0.30     1.25       5.24  0.87  3.33     1080     1   
51                   0.22     2.29       5.60  1.24  3.37     1265     1   
54                   0.21     1.62       5.85  0.92  3.20     1060     1   
55                   0.20     2.45       6.25  0.98  3.03     1120     1   
56                   0.26     2.03       6.38  0.94  3.31      970     1   
60                   0.63     0.41       3.27  1.25  1.67      680     2   
61                   0.53     0.62       5.75  0.98  1.59      450     2   
63                   0.19     1.87       4.45  1.22  2.87      420     2   
66                   0.26     2.28       5.30  1.12  3.18      502     2   
80                   0.30     1.43       2.50  1.38  3.12      278     2   
86                   0.43     1.56       2

In [102]:
df.shape

(36, 16)